import type { Metadata } from "next";

import "./globals.css";
import SocketContextProvider from "../context/SocketContext";
import SessionProvider from "../provider/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>
          <SocketContextProvider>{children}</SocketContextProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
